### ISSUE TITLE
Slight flicker (no pun intended) between last and first slide when looping.

### ISSUE THREAD

**Issue by 23d1** [metafizzy/flickity-fade#2] opened 2019-02-23 06:10 UTC
There seems to be a slight flicker when looping from the last to the first slide. Any idea on how to alleviate the issue? Perhaps a pure CSS solution (that's how I did fading prior, but it also had a visual bug when looping).

**Test case:** https://codepen.io/desandro/pen/azqbop

**Comment by 23d1** [comment] 2019-02-23 19:17
It now seems (after emptying my cache) that the issue has gone away. Sorry for the false alarm!

**Comment by desandro** [comment] 2019-02-24 16:28
Thank you for reporting this issue and for following up.

**Comment by 23d1** [comment] 2019-02-24 18:37
I guess it's technically still there if you rapidly tap/click to loop around, but seems to work fine if the transition to the last slide gets to finish before going around to the first slide.

**Comment by Geestig** [comment] 2019-04-11 07:28
I had this issue when I was using WrapAround: true in my options. Even though this has no use when using flickity-fade if I'm not mistaken?

**Comment by desandro** [comment] 2019-04-12 01:29
Closing as a duplicate of #1.

**Closed by desandro** 2019-04-12 01:29 UTC
